guard :rspec, cmd: 'bundle exec rspec --color' do 

	watch(%r{^spec/.+_spec\.rb$})
	watch(%r{^lib/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
	watch("server.rb") { |m| "spec/server_spec.rb"}
end


# run Guard through Bundler with:
# $ guard -i

# Guard will watch your files...if you change/save an rb file,
# it will automatically run the corresponding spec file