source "https://rubygems.org"

gem "sinatra"

gem "sinatra-contrib"
gem "imdb", :git => "https://github.com/nickborbe/imdb.git"

# ************


gem "rspec"
gem "rack"
gem "rack-test"


gem "guard"
gem "guard-rspec"
# ^ guard will run rspec if you make changes