# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f8f1b35e7e72b34455e74808c062ddb193aa4e11bd4c360ca4032be52cbfc9df784343db7a91fd37ce1215bf907bac0c93da2f521e4a8b46c879e014c78b33

test:
  secret_key_base: 61045a2aef515107a22a533d96185c63373b2f1ca27634e2dc099aa97975ff488ecb67993a885982cdeb6f72f4186d51eaf7574fd45425f13250f84b0a2a2a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
